-- FIX SCRIPT: Membuka akses tabel link_test_toefl agar bisa diedit (bisa insert, update)
-- Jalankan script ini di SQL Editor Supabase untuk memperbaiki masalah API Error 500 (RLS policy violation)

-- 1. Pastikan tabelnya ada, jika belum ada buat terlebih dahulu
CREATE TABLE IF NOT EXISTS public.link_test_toefl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saluran_whatsapp TEXT,
    saluran_telegram TEXT,
    grup TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Aktifkan RLS (jika belum)
ALTER TABLE public.link_test_toefl ENABLE ROW LEVEL SECURITY;

-- 3. Hapus policy lama jika ada yang terlalu ketat
DROP POLICY IF EXISTS "Enable read access for all users" ON public.link_test_toefl;
DROP POLICY IF EXISTS "Enable full access for all users" ON public.link_test_toefl;

-- 4. Buat policy baru yang mengizinkan semua operasi untuk public (seperti pada tabel lain di dashboard)
CREATE POLICY "Enable full access for all users" ON public.link_test_toefl
  FOR ALL USING (true) WITH CHECK (true);
