-- 1. Buat tabel program_packages
create table public.program_packages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  original_price text not null, -- Menyimpan format string seperti 'Rp 1.000.000'
  price text not null,          -- Menyimpan format string seperti 'Rp 499.000'
  is_best_value boolean default false
);

-- 2. Aktifkan Row Level Security (RLS)
alter table public.program_packages enable row level security;

-- 3. Buat policy akses (Sesuaikan dengan kebutuhan keamanan Anda)
-- Mengizinkan siapa saja untuk melihat data (Public Read)
create policy "Enable read access for all users" on public.program_packages
  for select using (true);

-- Mengizinkan user yang login untuk mengubah data (Authenticated Insert/Update/Delete)
create policy "Enable insert for authenticated users only" on public.program_packages
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.program_packages
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.program_packages
  for delete using (auth.role() = 'authenticated');

-- 4. Masukkan data awal (Seeding)
insert into public.program_packages (title, original_price, price, is_best_value)
values
  ('1 Minggu', 'Rp 1.000.000', 'Rp 499.000', false),
  ('2 Minggu', 'Rp 1.200.000', 'Rp 599.000', false),
  ('3 Minggu', 'Rp 1.400.000', 'Rp 699.000', false),
  ('1 Bulan', 'Rp 1.600.000', 'Rp 799.000', true),
  ('2 Bulan', 'Rp 3.100.000', 'Rp 1.550.000', false),
  ('3 Bulan', 'Rp 4.600.000', 'Rp 2.300.000', false);
